theme: jekyll-theme-slate

title: Optimization & Learning Approaches to Resource Allocation for Social Good 
description: A tutorial at AAMAS 2019 <br/> By Sanmay Das, John P Dickerson, and Bryan Wilder
